### ISSUE TITLE
What is S in your paper notation?

### ISSUE THREAD

**Issue by spk921** [yarotsky/voxelfeatures#1]
Hi, this is may not relevant to the code. However, I have found confusing regarding the notation on the paper. In your paper, there are "dS" on the question of SA, AN, QF, and EAD. What is "S" is meaning? I have look carefully but can't found the definition of the notation.

**Comment by yarotsky** [comment]
Hello, dS is the area element, i.e. \int f dS is just the integral of f over the surface area. Sorry about the confusion, I thought this was a standard notation (cf. https://en.wikipedia.org/wiki/Surface_integral).

**Comment by spk921** [comment]
Thank you for your answer.
